### ISSUE TITLE
Should the Saturday and Sunday be in the next sprint week?

### ISSUE THREAD

**Issue by LeftTwixWand** [onetocny/WhatSprintIsItCalendar#1]
Now the weekend days belong to the next sprint week, as shown on the screenshot:
<img width="942" alt="image" src="https://user-images.githubusercontent.com/50652041/211278901-cb6a4c23-a378-48d5-bf3b-926287bb0aa5.png">

Is it ok to be like this, or they should belong to the current sprint week?

**Comment by onetocny** [comment]
I wanted to be in line with WhatSprintIsIt. The sprints start on Friday/Saturday midnight [there](https://whatsprintis.it/calendar). You can also check their API to determine the beginning of the [first sprint](https://whatsprintis.it/sprint/1).

![Screenshot 2023-01-09 105245](https://user-images.githubusercontent.com/5574525/211281316-9fdfa6be-c558-4278-b829-73ca3109e77e.png)

**Comment by LeftTwixWand** [comment]
Ok, got it) Thank you💟
